FROM docker.pkg.github.com/checkmarx-ts/cxcli-docker/cxcli:latest

# Any certs with the extension .cer or .crt are imported
# automatically during the build when the base image is
# cxcli

WORKDIR /opt

#Copy Code

#COPY . ./mycode/

