name: Docker Image CI

env:
  DOCKER_GITHUB: "docker.pkg.github.com"
  PKG_NAME: "cxcli"
  REPOSITORY: "checkmarx-ts/cxcli-docker"
  CX_CLI_URL: "https://download.checkmarx.com/9.0.0/Plugins/CxConsolePlugin-2020.4.12.zip"

on:
  push:
    branches: 
      - master

jobs:
  latest:
    env:
      CX_CLI_VERSION: "latest"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        docker build -t $PKG_NAME:$CX_CLI_VERSION . --no-cache --build-arg CX_CLI_URL=$CX_CLI_URL
    - name: Tag Docker Image
      run: |
        docker tag $PKG_NAME:$CX_CLI_VERSION $DOCKER_GITHUB/$REPOSITORY/$PKG_NAME:$CX_CLI_VERSION
    - name: Docker Login
      run: |
        docker login $DOCKER_GITHUB -u $GITHUB_ACTOR -p ${{secrets.GITHUB_TOKEN}}
    - name: Docker Push
      run: |
        docker push $DOCKER_GITHUB/$REPOSITORY/$PKG_NAME:$CX_CLI_VERSION
  "_2020_4_12":
    env:
      CX_CLI_VERSION: "2020.4.12"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        docker build -t $PKG_NAME:$CX_CLI_VERSION . --no-cache --build-arg CX_CLI_URL=$CX_CLI_URL
    - name: Tag Docker Image
      run: |
        docker tag $PKG_NAME:$CX_CLI_VERSION $DOCKER_GITHUB/$REPOSITORY/$PKG_NAME:$CX_CLI_VERSION
    - name: Docker Login
      run: |
        docker login $DOCKER_GITHUB -u $GITHUB_ACTOR -p ${{secrets.GITHUB_TOKEN}}
    - name: Docker Push
      run: |
        docker push $DOCKER_GITHUB/$REPOSITORY/$PKG_NAME:$CX_CLI_VERSION
