name: Docker Image CI
env:
  REPO_NAME: "cxcli-docker"
  DOCKER_GITHUB: "docker.pkg.github.com"
  PKG_NAME: "cxcli"
on:
  push:
    branches: 
      - master
jobs:
  latest:
    env:
      CX_CLI_VERSION: "8.90.2"
      CX_VERSION: "8.9.0"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: |
        docker build -t $PKG_NAME:latest . --no-cache --build-arg CX_CLI_VERSION=$CX_CLI_VERSION --build-arg CX_VERSION=$CX_VERSION
    - name: Tag Docker Image
      run: |
        docker tag $PKG_NAME:latest $DOCKER_GITHUB/$GITHUB_ACTOR/$REPO_NAME/$PKG_NAME:latest
        docker tag $PKG_NAME:latest $GITHUB_ACTOR/$PKG_NAME:latest
    - name: Docker Login
      run: |
        docker login $DOCKER_GITHUB -u $GITHUB_ACTOR -p ${{secrets.GITHUB_TOKEN}}
        docker login -u $GITHUB_ACTOR -p ${{secrets.DOCKER_PASSWORD}}
    - name: Docker Push
      run: |
        docker push $DOCKER_GITHUB/$GITHUB_ACTOR/$REPO_NAME/$PKG_NAME:latest
        docker push $GITHUB_ACTOR/$PKG_NAME:latest
  "_8_9_0":
    env:
      CX_CLI_VERSION: "8.90.2"
      CX_VERSION: "8.9.0"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: |
        docker build -t $PKG_NAME:$CX_CLI_VERSION . --no-cache --build-arg CX_CLI_VERSION=$CX_CLI_VERSION --build-arg CX_VERSION=$CX_VERSION 
    - name: Tag Docker Image 
      run: |
        docker tag $PKG_NAME:$CX_CLI_VERSION $DOCKER_GITHUB/$GITHUB_ACTOR/$REPO_NAME/$PKG_NAME:$CX_CLI_VERSION
        docker tag $PKG_NAME:$CX_CLI_VERSION $GITHUB_ACTOR/$PKG_NAME:$CX_CLI_VERSION
    - name: Docker Login
      run: |
        docker login $DOCKER_GITHUB -u $GITHUB_ACTOR -p ${{secrets.GITHUB_TOKEN}}
        docker login -u $GITHUB_ACTOR -p ${{secrets.DOCKER_PASSWORD}}
    - name: Docker Push
      run: |
        docker push $DOCKER_GITHUB/$GITHUB_ACTOR/$REPO_NAME/$PKG_NAME:$CX_CLI_VERSION
        docker push $GITHUB_ACTOR/$PKG_NAME:$CX_CLI_VERSION
  "_8_8_0":
    env:
      CX_CLI_VERSION: "8.80.2"
      CX_VERSION: "8.8.0"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: |
        docker build -t $PKG_NAME:$CX_CLI_VERSION . --no-cache --build-arg CX_CLI_VERSION=$CX_CLI_VERSION --build-arg CX_VERSION=$CX_VERSION
    - name: Tag Docker Image
      run: |
        docker tag $PKG_NAME:$CX_CLI_VERSION $DOCKER_GITHUB/$GITHUB_ACTOR/$REPO_NAME/$PKG_NAME:$CX_CLI_VERSION
        docker tag $PKG_NAME:$CX_CLI_VERSION $GITHUB_ACTOR/$PKG_NAME:$CX_CLI_VERSION
    - name: Docker Login
      run: |
        docker login $DOCKER_GITHUB -u $GITHUB_ACTOR -p ${{secrets.GITHUB_TOKEN}}
        docker login -u $GITHUB_ACTOR -p ${{secrets.DOCKER_PASSWORD}}
    - name: Docker Push
      run: |
        docker push $DOCKER_GITHUB/$GITHUB_ACTOR/$REPO_NAME/$PKG_NAME:$CX_CLI_VERSION
        docker push $GITHUB_ACTOR/$PKG_NAME:$CX_CLI_VERSION
  "_8_7_0":
    env:
      CX_CLI_VERSION: "8.70.4"
      CX_VERSION: "8.7.0"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: |
        docker build -t $PKG_NAME:$CX_CLI_VERSION . --no-cache --build-arg CX_CLI_VERSION=$CX_CLI_VERSION --build-arg CX_VERSION=$CX_VERSION
    - name: Tag Docker Image
      run: |
        docker tag $PKG_NAME:$CX_CLI_VERSION $DOCKER_GITHUB/$GITHUB_ACTOR/$REPO_NAME/$PKG_NAME:$CX_CLI_VERSION
        docker tag $PKG_NAME:$CX_CLI_VERSION $GITHUB_ACTOR/$PKG_NAME:$CX_CLI_VERSION
    - name: Docker Login
      run: |
        docker login $DOCKER_GITHUB -u $GITHUB_ACTOR -p ${{secrets.GITHUB_TOKEN}}
        docker login -u $GITHUB_ACTOR -p ${{secrets.DOCKER_PASSWORD}}
    - name: Docker Push
      run: |
        docker push $DOCKER_GITHUB/$GITHUB_ACTOR/$REPO_NAME/$PKG_NAME:$CX_CLI_VERSION
        docker push $GITHUB_ACTOR/$PKG_NAME:$CX_CLI_VERSION
  "_8_6_0":
    env:
      CX_CLI_VERSION: "8.60.3"
      CX_VERSION: "8.6.0"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: |
        docker build -t $PKG_NAME:$CX_CLI_VERSION . --no-cache --build-arg CX_CLI_VERSION=$CX_CLI_VERSION --build-arg CX_VERSION=$CX_VERSION
    - name: Tag Docker Image
      run: |
        docker tag $PKG_NAME:$CX_CLI_VERSION $DOCKER_GITHUB/$GITHUB_ACTOR/$REPO_NAME/$PKG_NAME:$CX_CLI_VERSION
        docker tag $PKG_NAME:$CX_CLI_VERSION $GITHUB_ACTOR/$PKG_NAME:$CX_CLI_VERSION
    - name: Docker Login
      run: |
        docker login $DOCKER_GITHUB -u $GITHUB_ACTOR -p ${{secrets.GITHUB_TOKEN}}
        docker login -u $GITHUB_ACTOR -p ${{secrets.DOCKER_PASSWORD}}
    - name: Docker Push
      run: |
        docker push $DOCKER_GITHUB/$GITHUB_ACTOR/$REPO_NAME/$PKG_NAME:$CX_CLI_VERSION
        docker push $GITHUB_ACTOR/$PKG_NAME:$CX_CLI_VERSION
